### ISSUE TITLE
Selected Date Differs 1 Day

### ISSUE THREAD

**Issue by takeruadelbert** [maggialejandro/react-native-calendario#176]
Hi, I would like to report a possibly bug.
when I select the date of the calendar, it's always behind a day in my case.
Could you explain this problem?

for instance, I select July 2nd, 2020. however the console log shows **_"startDate": 2020-07-01T17:00:00.000Z_**

_P.S. I am using Android device anyway._

**Image Selected Date**
![image](https://user-images.githubusercontent.com/17585173/86349518-70f80580-bc8b-11ea-94cc-0f1060c63d77.png)

**Image Console Output**
![image](https://user-images.githubusercontent.com/17585173/86349692-bfa59f80-bc8b-11ea-8ff1-f23289d9ca49.png)

**Comment by maggialejandro** [comment]
Hi @takeruadelbert 
Could you provide a code sample? which version are you using? is remote debug enabled?

**Comment by nervouscat** [comment]
Hi @maggialejandro 

its currently happening on version 2.1.0

**Comment by EthanJoyce** [comment]
I've had this issue multiple times, but I don't believe it to be related to this library.

For me, it was how I was converting dates to string, and then back to date objects. Specifically, I was using UTC time to create new Dates, resulting in a different day due to timezones.

Play around with the different Date functions, as they often give unexpected results. I'm not sure why, but the JavaScript Date library is wonky, and it's always a pain to work with.

**Comment by takeruadelbert** [comment]
@EthanJoyce I think you are right, JavaScript Date Library kinda suck, I had to set the proper timezone.
