### ISSUE TITLE
Range Selection

### ISSUE THREAD

**Issue by arunkumar-pyt** [maggialejandro/react-native-calendario#378]
Range selection on different month is reset all the state initially

**Comment by alexandre-carvalho** [comment]
Same problem reported by @arunkumar-pyt 
Used Version: "^3.5.0"

**Comment by arunkumar-pyt** [comment]
Any update ?

**Comment by maggialejandro** [comment]
Hi guys, sorry for the delay.
To better understand and address it, it would be incredibly helpful if you could provide a reproducible example that demonstrates the problem you're encountering.
Also a video recording would be helpful.

Thanks in advance

**Comment by rswingler** [comment]
Steps to reproduce the issue:
- Provide startDate and endDate state variables for the Calendar component
- Provide an onPress function that sets the startDate on first press, and the endDate if startDate is present
- While viewing the calendar, press on any date in the first month to select a "start date"
- Press on any date in the second month to select an "end date"
- You will see the second date selected as the startDate, even though it should have populated the endDate and created a date range
- The first "press" on a given month is not being respected for creating a date range (subsequent presses do work)
- Once a date range has successfully been created within a given month, then this error is no longer reproducible for that month (the issue is one-off per month)

https://github.com/maggialejandro/react-native-calendario/assets/5535496/aea3a9fc-cdc9-4b16-89a5-40c46b50da6e

**Comment by maggialejandro** [comment]
Can you try this please?

```typescript
type Range = {
  start?: Date;
  end?: Date;
};

const [range, setRange] = useState<Range>({
  start: START_DATE,
  end: END_DATE,
});

const handleChangeDate = useCallback((date) => {
  setRange((prevRange) => {
    if (prevRange?.start) {
      if (prevRange.end) {
        return {
          start: date,
          end: undefined,
        };
      } else if (date < prevRange.start) {
        return {
          start: date,
          end: prevRange.end,
        };
      } else if (date > prevRange.start) {
        return {
          start: prevRange.start,
          end: date,
        };
      } else {
        return {
          start: date,
          end: date,
        };
      }
    } else {
      return {
        start: date,
      };
    }
  });
}, []);

```

**Comment by rswingler** [comment]
@maggialejandro Your solution worked! I'm able to create a date range between months on the first press. Thank you!

**Comment by maggialejandro** [comment]
Awesome!
